project:
  type: website
  output-dir: docs
website:
  title: "The elephant of surprise"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/SergeiOssokine
format:
  html:
    theme: cosmo
    css: styles.css



